name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
#        tags: ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
        tags: ghcr.io/${{ github.repository }}:latest      
